# Example: new test suite generated by lisa-mcp-server
# Area: network — verifies basic connectivity and interface health
"""
NetworkConnectivity — verifies basic Linux network interface health.
"""

from __future__ import annotations

from logging import Logger
from typing import Any

from lisa import (
    Environment,
    Node,
    TestCaseMetadata,
    TestSuite,
    TestSuiteMetadata,
    assert_that,
    simple_requirement,
)
from lisa.environment import EnvironmentStatus


@TestSuiteMetadata(
    area="network",
    category="functional",
    description="Verifies basic Linux network interface health and connectivity.",
    owner="your-team",
)
class NetworkConnectivity(TestSuite):
    """
    Basic network connectivity tests suitable for smoke-testing any Linux image.
    """

    @TestCaseMetadata(
        description="Verifies at least one non-loopback network interface is UP.",
        priority=0,
        timeout=300,
        use_new_environment=False,
        requirement=simple_requirement(
            environment_status=EnvironmentStatus.Deployed,
        ),
    )
    def verify_interface_up(
        self,
        case_name: str,
        node: Node,
        environment: Environment,
        log: Logger,
    ) -> None:
        result = node.execute("ip link show | grep -c 'state UP'", expected_exit_code=0)
        count = int(result.stdout.strip())
        assert_that(count).described_as("number of UP interfaces").is_greater_than(0)

    @TestCaseMetadata(
        description="Verifies outbound internet connectivity via DNS resolution.",
        priority=1,
        timeout=120,
        use_new_environment=False,
        requirement=simple_requirement(),
    )
    def verify_dns_resolution(
        self,
        case_name: str,
        node: Node,
        environment: Environment,
        log: Logger,
    ) -> None:
        result = node.execute("nslookup microsoft.com", expected_exit_code=0)
        assert_that(result.stdout).described_as("nslookup output").contains("Address")

    @TestCaseMetadata(
        description="Verifies network throughput with iperf3 (requires iperf3 installed).",
        priority=2,
        timeout=600,
        use_new_environment=True,
        requirement=simple_requirement(
            min_core_count=2,
        ),
    )
    def verify_network_throughput(
        self,
        case_name: str,
        node: Node,
        environment: Environment,
        log: Logger,
    ) -> None:
        node.execute("which iperf3 || apt-get install -y iperf3", sudo=True)
        result = node.execute("iperf3 -c iperf.he.net -t 10 --json", expected_exit_code=0)
        log.info("iperf3 output captured; further parsing can be added here.")

    def before_case(self, **kwargs: Any) -> None:
        pass

    def after_case(self, **kwargs: Any) -> None:
        pass
